name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: [self-hosted, solinas]
    container:
        image: node:22

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        #with:
        #  submodules: recursive
      - name: Check protos dir
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          ls -la protobuf || echo "protobuf/ not found"

      - name: Install Protobuf
        run: apt-get update -y && apt-get install protobuf-compiler -y

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Lint code
        run: npm run lint

      #- name: Build TypeScript
      #  run: npm run build

      - name: Run tests
        run: npm test
